name: my_diary_front
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # google_map
  google_maps_flutter: ^2.2.1
  flutter_google_places: ^0.3.0
  # location
  location: ^4.4.0
  # http
  dio: ^4.0.6
  #swipe animation
  flutter_swiper: ^1.1.6
  swipe_cards: ^1.0.0
  # firebase_google
  google_sign_in: ^5.4.2
  # firebase
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  # firebase_kakao
  flutter_web_auth: ^0.5.0
  uuid: ^3.0.6
  flutter_secure_storage: ^6.0.0
  # .env
  flutter_dotenv: ^5.0.2
  # floating action bubble
  floating_action_bubble: ^1.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - .env
    - img/naver_icon.png
    - img/kakao_icon.png
    - img/google_icon.png